const express = require("express");
const router = express.Router();
const { protectAdmin, authorizeRoles } = require("../middleware/adminMiddleware");

const adminAuthRoutes = require("./admin/adminAuth");
const adminUserRoutes = require("./admin/adminUser");
const adminDashboardRoutes = require("./admin/adminDashboard");
const adminContentRoutes = require("./admin/adminContent");
const adminMarketplaceRoutes = require("./admin/adminMarketplace");
const adminJobRoutes = require("./admin/adminJobs");
const adminStoriesFeedRoutes = require("./admin/adminStoriesFeed");
const adminSubscriptionRoutes = require("./admin/adminSubscriptions");
const adminNotificationRoutes = require("./admin/adminNotifications");
const adminReviewRoutes = require("./admin/adminReviews");
const adminRewardsRoutes = require("./admin/adminRewards");
const adminReferralRoutes = require("./admin/adminReferrals");
const adminAnalyticsRoutes = require("./admin/adminAnalytics");
const adminSubAdminRoutes = require("./admin/adminSubAdmin");
const adminCouponRoutes = require("./admin/adminCoupons");
const adminSupportRoutes = require("./admin/adminSupport");
const adminBookingRoutes = require("./admin/adminBookings");
const adminVerificationRoutes = require("./admin/adminVerification");
const adminSettingsRoutes = require("./admin/adminSettings");
const adminAuditRoutes = require("./admin/adminAudit");
const adminQARoutes = require("./admin/adminQA");
const adminModerationRoutes = require("./admin/adminModeration");
const adminExtraRoutes = require("./admin/adminExtras");
const adminImpersonateRoutes = require("./admin/adminImpersonate");
const adminAlertRoutes = require("./admin/adminAlerts");
const adminFraudRoutes = require("./admin/adminFraud");
const adminCampaignRoutes = require("./admin/adminCampaigns");
const adminHeatmapRoutes = require("./admin/adminHeatmap");
const adminChurnRoutes = require("./admin/adminChurn");
const adminApiKeyRoutes = require("./admin/adminApiKeys");
const adminContentScheduleRoutes = require("./admin/adminContentSchedule");

router.use("/", adminAuthRoutes);
router.use("/", adminUserRoutes);
router.use("/", adminDashboardRoutes);
router.use("/", adminContentRoutes);
router.use("/", adminMarketplaceRoutes);
router.use("/", adminJobRoutes);
router.use("/", adminStoriesFeedRoutes);
router.use("/", adminSubscriptionRoutes);
router.use("/", adminReviewRoutes);
router.use("/rewards", adminRewardsRoutes);
router.use("/", adminReferralRoutes);
router.use("/analytics", protectAdmin, authorizeRoles("superadmin"), adminAnalyticsRoutes);
router.use("/notifications", adminNotificationRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminSubAdminRoutes);
router.use("/", adminCouponRoutes);
router.use("/", adminSupportRoutes);
router.use("/", adminBookingRoutes);
router.use("/", adminVerificationRoutes);
router.use("/", adminSettingsRoutes);
router.use("/", adminAuditRoutes);
router.use("/", adminQARoutes);
router.use("/", adminModerationRoutes);
router.use("/", adminExtraRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminImpersonateRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminAlertRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminFraudRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminCampaignRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminHeatmapRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminChurnRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminApiKeyRoutes);
router.use("/", protectAdmin, authorizeRoles("superadmin"), adminContentScheduleRoutes);

module.exports = router;
