const express = require("express");
const router = express.Router();

const adminAuthRoutes = require("./admin/adminAuth");
const adminUserRoutes = require("./admin/adminUser");
const adminDashboardRoutes = require("./admin/adminDashboard");
const adminContentRoutes = require("./admin/adminContent");
const adminMarketplaceRoutes = require("./admin/adminMarketplace");
const adminJobRoutes = require("./admin/adminJobs");
const adminStoriesFeedRoutes = require("./admin/adminStoriesFeed");
const adminSubscriptionRoutes = require("./admin/adminSubscriptions");
const adminNotificationRoutes = require("./admin/adminNotifications");
const adminReviewRoutes = require("./admin/adminReviews");
const adminRewardsRoutes = require("./admin/adminRewards");
const adminReferralRoutes = require("./admin/adminReferrals");
const adminAnalyticsRoutes = require("./admin/adminAnalytics");
const adminSubAdminRoutes = require("./admin/adminSubAdmin");
const adminCouponRoutes = require("./admin/adminCoupons");
const adminSupportRoutes = require("./admin/adminSupport");
const adminBookingRoutes = require("./admin/adminBookings");
const adminVerificationRoutes = require("./admin/adminVerification");
const adminSettingsRoutes = require("./admin/adminSettings");
const adminAuditRoutes = require("./admin/adminAudit");
const adminQARoutes = require("./admin/adminQA");
const adminModerationRoutes = require("./admin/adminModeration");
const adminExtraRoutes = require("./admin/adminExtras");

router.use("/", adminAuthRoutes);
router.use("/", adminUserRoutes);
router.use("/", adminDashboardRoutes);
router.use("/", adminContentRoutes);
router.use("/", adminMarketplaceRoutes);
router.use("/", adminJobRoutes);
router.use("/", adminStoriesFeedRoutes);
router.use("/", adminSubscriptionRoutes);
router.use("/", adminReviewRoutes);
router.use("/rewards", adminRewardsRoutes);
router.use("/", adminReferralRoutes);
router.use("/analytics", adminAnalyticsRoutes);
router.use("/notifications", adminNotificationRoutes);
router.use("/", adminSubAdminRoutes);
router.use("/", adminCouponRoutes);
router.use("/", adminSupportRoutes);
router.use("/", adminBookingRoutes);
router.use("/", adminVerificationRoutes);
router.use("/", adminSettingsRoutes);
router.use("/", adminAuditRoutes);
router.use("/", adminQARoutes);
router.use("/", adminModerationRoutes);
router.use("/", adminExtraRoutes);

module.exports = router;
